import type { NarrativeEvent } from './types';

export const EVENTS: NarrativeEvent[] = [
  {
    id: 'rain-at-training',
    tier: 'flavour',
    category: 'weather',
    title: 'Rain at training',
    body: 'The covers stayed on all morning and the squad settled for indoor nets.',
    weight: 3,
    cooldownDays: 3,
  },
  {
    id: 'green-top',
    tier: 'flavour',
    category: 'weather',
    title: 'A green top awaits',
    body: 'The curator has left a little grass on it. The seamers are grinning.',
    weight: 3,
    cooldownDays: 4,
  },
  {
    id: 'fan-mail',
    tier: 'flavour',
    category: 'fans',
    title: 'The postbag is full',
    body: 'Letters from the terraces pile up in the dressing room, mostly kind.',
    weight: 2,
    cooldownDays: 5,
  },
  {
    id: 'squad-illness',
    tier: 'context',
    category: 'player',
    title: 'Bug sweeps the camp',
    body: 'A sickness has moved through the squad and several players are below par.',
    weight: 2,
    cooldownDays: 6,
    conditions: { maxMorale: 65 },
    effects: { morale: -5, form: -3 },
  },
  {
    id: 'board-pressure',
    tier: 'context',
    category: 'board',
    title: 'Questions from above',
    body: 'The board has asked for a plan after a run of unconvincing displays.',
    weight: 2,
    cooldownDays: 6,
    conditions: { maxBoardConfidence: 45 },
    effects: { boardConfidence: -3, morale: -2 },
  },
  {
    id: 'hometown-hero',
    tier: 'context',
    category: 'fans',
    title: 'Local hero in form',
    body: 'A young local has the crowd on their feet and the mood is buoyant.',
    weight: 2,
    cooldownDays: 5,
    conditions: { minForm: 60 },
    effects: { morale: 4, reputation: 2 },
  },
  {
    id: 'media-hype',
    tier: 'context',
    category: 'media',
    title: 'The press like what they see',
    body: 'Back-page writers are calling this side the most watchable in years.',
    weight: 2,
    cooldownDays: 5,
    conditions: { minForm: 70 },
    effects: { reputation: 3, morale: 2 },
  },
  {
    id: 'star-criticises-selection',
    tier: 'story',
    category: 'player',
    title: 'Star questions selection',
    body: 'A senior player has gone public with frustration about the make-up of the side.',
    weight: 3,
    cooldownDays: 8,
    conditions: { maxMorale: 55 },
    choices: [
      {
        id: 'back-publicly',
        text: 'Back the player publicly',
        tone: 'positive',
        effects: { morale: 5, boardConfidence: -2 },
        response: 'The dressing room relaxes; the board notes who is really in charge.',
      },
      {
        id: 'private-word',
        text: 'Have a quiet word',
        tone: 'neutral',
        effects: { morale: 1 },
        response: 'The matter is settled behind closed doors.',
      },
      {
        id: 'discipline',
        text: 'Fine and drop him',
        tone: 'aggressive',
        effects: { morale: -6, boardConfidence: 4, reputation: -1 },
        response: 'Order is restored, but the squad is uneasy.',
      },
    ],
  },
  {
    id: 'transfer-rumour',
    tier: 'story',
    category: 'media',
    title: 'Rivals circle the star',
    body: 'A headline claims a rival franchise is preparing a record bid for your best player.',
    weight: 3,
    cooldownDays: 8,
    conditions: { minReputation: 55 },
    choices: [
      {
        id: 'hands-off',
        text: 'Declare him not for sale',
        tone: 'aggressive',
        effects: { reputation: 2, morale: 2 },
        response: 'The fans love the defiance; the agent is less pleased.',
      },
      {
        id: 'no-comment',
        text: 'Refuse to be drawn',
        tone: 'defensive',
        effects: { morale: -1 },
        response: 'The story rumbles on for another day.',
      },
    ],
  },
  {
    id: 'captaincy-doubt',
    tier: 'story',
    category: 'media',
    title: 'Captaincy under the spotlight',
    body: 'Pundits are asking whether the captain still has the dressing room.',
    weight: 2,
    cooldownDays: 8,
    conditions: { maxBoardConfidence: 50 },
    choices: [
      {
        id: 'back-captain',
        text: 'Give the captain full backing',
        tone: 'positive',
        effects: { morale: 4, boardConfidence: 1 },
        response: 'A note of stability in a noisy week.',
      },
      {
        id: 'review',
        text: 'Say it will be reviewed at season end',
        tone: 'defensive',
        effects: { morale: -3, boardConfidence: 2 },
        response: 'The speculation only intensifies.',
      },
    ],
  },
];
