import type { FormatId, FormatSpec } from './types';

export const FORMATS: Record<FormatId, FormatSpec> = {
  test: {
    id: 'test',
    name: 'Test',
    ballsPerOver: 6,
    inningsPerTeam: 2,
    maxOversPerInnings: null,
    maxDays: 5,
    maxOversPerDay: 90,
    hasDeclarations: true,
    hasFollowOn: true,
    followOnRuns: 200,
    hasPowerplay: false,
    hasFreeHit: false,
    usesDls: false,
    newBallOvers: 80,
    ballColour: 'red',
  },
  odi: {
    id: 'odi',
    name: 'ODI',
    ballsPerOver: 6,
    inningsPerTeam: 1,
    maxOversPerInnings: 50,
    maxDays: 1,
    maxOversPerDay: null,
    hasDeclarations: false,
    hasFollowOn: false,
    followOnRuns: null,
    hasPowerplay: true,
    hasFreeHit: true,
    usesDls: true,
    newBallOvers: null,
    ballColour: 'white',
  },
  t20: {
    id: 't20',
    name: 'T20',
    ballsPerOver: 6,
    inningsPerTeam: 1,
    maxOversPerInnings: 20,
    maxDays: 1,
    maxOversPerDay: null,
    hasDeclarations: false,
    hasFollowOn: false,
    followOnRuns: null,
    hasPowerplay: true,
    hasFreeHit: true,
    usesDls: true,
    newBallOvers: null,
    ballColour: 'white',
  },
};
